### ISSUE TITLE
Now who's to blame? - pack.mcmeta missing comma

### ISSUE THREAD

**Issue by joklbash** [TelepathicGrunt/Blame#10]
There's a missing comma in your pack file. It leads to error messages popping up on client side in 1.7.0. Thanks for the great mod.

**Comment by TelepathicGrunt** [comment]
Thank you for letting me know. Not sure how it was able to run in dev

Fix has been released:  https://www.curseforge.com/minecraft/mc-mods/blame/files/3121791
