### ISSUE TITLE
Lil error.

### ISSUE THREAD

**Issue by K0-RR** [TelepathicGrunt/Blame#16]
[main/WARN]: @Mixin target net/minecraft/class_3778$class_4182 is public in blame.mixins.json:StructurePoolBasedGeneratorStructurePoolGeneratorMixin and should be specified in value

**Comment by TelepathicGrunt** [comment]
is this in production or in a dev environment?

**Comment by K0-RR** [comment]
Production, if I understand correctly what that means (for clarification - downloaded from the curseforge)

**Comment by TelepathicGrunt** [comment]
i asked some friends and it seems this can be safely ignored. The mixin is working just fine and this is just a small warning letting you know another mod may had access widened the class I mixin into (hence why it says the class is now public).

Nothing to worry about lol
