### ISSUE TITLE
Unregistered stuff summary is broken?

### ISSUE THREAD

**Issue by K0-RR** [TelepathicGrunt/Blame#21]
I will add more details later when I will have more time. Please see https://github.com/hYdos/Lint/issues/53 and https://github.com/SuperCoder7979/ecotones/issues/8

**Comment by TelepathicGrunt** [comment]
Closing as those two mods configuredfeatures were indeed not registered lol. Feel free to reach out to me if anymore devs gets confused by Blame! The registration for configuredfeatures is quite tricky and very easy to miss steps.
