### ISSUE TITLE
Crashes unable to explain certain areas, not useful on others - Fabric

### ISSUE THREAD

**Issue by amusingimpala75** [TelepathicGrunt/Blame#32]
When registering json, I came across and issue, there was much useless logspam about features in biomes "not being a json object", so I was recommended to try this.
When installed, some of the new crash info was helpful, but a lot of it was not. When the feature was flagged, it would also decide it needed to list out all of the other issues, even when going on later to explain them.
[Here's part of the crash log](https://gist.github.com/amusingimpala75/3ad6d590b0ecc0adcfb167bf29db941d) (which was originally 14000 lines long), and [Here's the code repo for it](https://github.com/amusingimpala75/TerraFirmaCraft/tree/1.16.x-fabric)

**Comment by TelepathicGrunt** [comment]
when the codec explodes, it propagates the error through all the other codecs while still trying to parse the biome which leads to this. 

however, you said "When registering json" and my first question is, "why?" lol. The json configuredfeatures will automatically register themselves so you shouldn't be doing any manual registering.

Edit: it would also be more helpful to have the entire log instead of a snippet too lol.

**Comment by amusingimpala75** [comment]
Registering json was probably the wrong way to put it, I meant having the jsons in the data/ dir. If you want the entire log, I will try to get it up, just that it is large
[latest.log](https://github.com/TelepathicGrunt/Blame/files/5985321/latest.log)

**Comment by TelepathicGrunt** [comment]
Looking at the very first error in the log, it seems the issue stems mostly from this
https://github.com/amusingimpala75/TerraFirmaCraft/blob/1.16.x-fabric/src/main/resources/data/tfc/worldgen/configured_surface_builder/volcanic_canyons.json#L4-L6

The custom codec for this may be incorrect or that this is being registered before the canyon is being made. tbh, i would not do reference like this and would opt for duplicating the surfacebuilder itself and give it different blockstates

**Comment by amusingimpala75** [comment]
Yup, lazy loading and caching the idea for registry lookup later fixed the issue
