### ISSUE TITLE
Blame don't work on new Forge 1.16.5 - 36.1.18

### ISSUE THREAD

**Issue by FrenchBoyi** [TelepathicGrunt/Blame#36]
When i launch the game in this new version of forge, it crash immediately

**Comment by TelepathicGrunt** [comment]
Yeah probably because forge’s latest update patched the flat chunk generator crash which means blame’s mixin to the same spot now breaks. I think I’ll just remove that feature of blame since forge is handling that crash now.

I’ll release an update tomorrow when I wake up

**Comment by TelepathicGrunt** [comment]
fixed in v3.0.1 blame! Thank you for your report!
