### ISSUE TITLE
1.16.3-1.4.5 Blame crashes on non-oracle java version. Fix coming ASAP

### ISSUE THREAD

**Issue by BedrockLegends** [TelepathicGrunt/Blame#4]
I updated this to the latest version on cruse and as soon as I updated it crashed

[crash-2020-10-20_18.05.01-client.txt](https://github.com/TelepathicGrunt/Blame/files/5412142/crash-2020-10-20_18.05.01-client.txt)

**Comment by TelepathicGrunt** [comment]
Thank you for reporting this! Ok so it seems to be caused by my mixin conflicting with someone else's coremod. Do you have a modlist that I can check out and try to find the conflicting mod? It would also make it easier and faster if you are able to export the mod profile or let me know what modpack this is so I can download it.

**Comment by BedrockLegends** [comment]
[Uploading Journey Across The Void 2-1.7.zip…]()

**Comment by TelepathicGrunt** [comment]
Ok after more tested, blame works perfectly with your mod pack with vanilla launcher. But blame alone in GDLauncher crash. wtf???

What launcher are you using? GDLauncher too?

**Comment by TelepathicGrunt** [comment]
Ok so I found it is this mixin that is crashing when ran on GDLauncher... oof.
https://github.com/TelepathicGrunt/Blame/blob/9b356c6cdf5b81a6c68d9077c31878f03dcecb70/src/main/java/com/telepathicgrunt/blame/mixin/JigsawPatternMixin.java#L35-L46

Thank you for letting me know so fast before it broke everyone else! Just use the previous version of Blame for now while I try and think of an alternative way to do this mixin to make missing nbt files be able to say what structure pool tried calling them

**Comment by TelepathicGrunt** [comment]
Actually, it is working with Multimc and Twitch launcher too. It's only GDLauncher that is failing. Huh. You can use the latest Blame but you have to use a different launcher if you do so. hmmm

**Comment by TelepathicGrunt** [comment]
Ok good news, it's just the java version currently shipped with GDLauncher. If you go to settings, java, turn off autodetect java path, and select your own java version, Blame should not crash GDLauncher anymore. Seems the java version they shipped has some bugs or something.

**Comment by TelepathicGrunt** [comment]
Hey, @BedrockLegends @V-Boy, can either of you test this jar to see if this fixed the crash?
[blame-1.16.3-1.4.6b.zip](https://github.com/TelepathicGrunt/Blame/files/5425497/blame-1.16.3-1.4.6b.zip)

**Comment by BugmanBugman** [comment]
Yeah can confirm it works for me

**Comment by TelepathicGrunt** [comment]
Amazing lmao. The issue the whole time was I was doing
`import javafx.util.Pair;` which only works on certain java versions I meant to use `import com.mojang.datafixers.util.Pair;` but I screwed up. This is 100% my fault. Fixed release coming shortly

**Comment by TelepathicGrunt** [comment]
[blame-forge-1.16.3-1.4.6](https://www.curseforge.com/minecraft/mc-mods/blame/files/3089940) is now approved on curseforge! Sorry about that everyone but thank you for being patient with me. I'm definitely not gonna make the mistake of importing javafx ever again lmao
