### ISSUE TITLE
1.17 support?

### ISSUE THREAD

**Issue by MenacingPerson** [TelepathicGrunt/Blame#40]
Title is pretty self-explanatory 🤷

**Comment by TelepathicGrunt** [comment]
Forge isn't even out yet for 1.17 lol. So 1.17 forge blame isn't possible right now anyway. When it does release, I would need to find time to update and see which report are still valid to do and which was patched by mojang. And I got other mods I want to update too when i have some free time lol. Lots to do, so little time

**Comment by MenacingPerson** [comment]
I'm talking about the fabric version, probably should have mentioned that
.

**Comment by TelepathicGrunt** [comment]
my bad. I still need time lol. I'll close this when blame 1.17 release is out so you can get notified of it

**Comment by TelepathicGrunt** [comment]
1.17 fabric is out but is most likely buggy. please make issue reports if it crashes or explodes lol. I had issues with getting some of the mixins to work
