### ISSUE TITLE
Unclear "MissingRegistry" Error

### ISSUE THREAD

**Issue by Derpford** [TelepathicGrunt/Blame#42]
I'm having a confusingly-worded error on worldgen, and Blame does not appear to be showing any info about the crash. Note that I have NotEnoughCrashes installed as well, so I'm not sure if that's affecting the result.

Also, Minecraft does not close after crashing like this, with *or* without NEC. In fact, it never leaves the loading screen; I have to manually end the task.

I don't know what mod is causing this; I've removed a couple worldgen mods as blind guesses, but this is quickly getting very frustrating.

See attached my log file:
[latest.log](https://github.com/TelepathicGrunt/Blame/files/6805906/latest.log)

**Comment by Derpford** [comment]
Another log, this time with almost all of my biome mods disabled. I'm struggling to keep track of which mods are adding what features, sadly...
[latest.log](https://github.com/TelepathicGrunt/Blame/files/6805938/latest.log)

**Comment by TelepathicGrunt** [comment]
Can you please remove notenoughcrashes and then get the crash again? Then give me the latest.log file. Notenoughcrashes is crashing trying to show what is crashing and thus, ends up hiding the real crash log

**Comment by Derpford** [comment]
All of these crashes were caused using the same seed and worldgen settings, so it *should* be the same worldgen feature causing it each time.

That said: I see BetterMineshafts in the stack trace now. Makes me sad; BetterMineshafts is one of my favorites.
[latest.log](https://github.com/TelepathicGrunt/Blame/files/6805972/latest.log)

**Comment by Derpford** [comment]
Removing all of Yung's mods led to successful worldgen.

**Comment by TelepathicGrunt** [comment]
Looks like it might be something with the furnace or item being set in the furnace within a Better Mineshaft. Have you tried deleting all of Better Mineshaft's configs to see if it is a corrupted config? 

![image](https://user-images.githubusercontent.com/40846040/125393056-3f714a00-e375-11eb-80b3-f5828cd9e602.png)


If deleting the config doesn't work, I can poke yung's to let him know to check out your log here as that is code it is crashing on cook timer

**Comment by Derpford** [comment]
If it's the cooking timer specifically, then I think I know what the problem is! I have [Hot Furnace](https://www.curseforge.com/minecraft/mc-mods/hot-furnace) installed, which changes furnace speed based on the power of the fuel that's inserted. That explains why I haven't run into this issue before--I've never used Hot Furnace and BetterMineshafts at the same time before.

**Comment by TelepathicGrunt** [comment]
oh. try removing it and if it does resolve the issue, Hot Furnace may want to know about this in case they are blowing up other mods we well

**Comment by Derpford** [comment]
The world generates successfully when loaded with Yung's mods and without Hot Furnace. I've opened up an issue on Hot Furnace's [issue tracker](https://github.com/Focamacho/HotFurnace/issues/1). Thanks for your help! I'm closing this issue, since the confusing error message was dealt with (and was caused by NEC, not by Blame).
