### ISSUE TITLE
Crash when loading up with the latest version of AutoRegLib for 1.16.3

### ISSUE THREAD

**Issue by BugmanBugman** [TelepathicGrunt/Blame#5]
https://hatebin.com/ludfpocchq
Seems like AutoRegLib does something that messes with the latest version of Blame v1.4.5.

**Comment by TelepathicGrunt** [comment]
Which version of blame are you using and does blame crash on its own with no other mod on?

**Comment by BugmanBugman** [comment]
It’s 1.16.3-1.4.5, and yeah I tested it with only autoreglib and blame, still crashes on load up

**Comment by TelepathicGrunt** [comment]
I mean without autoreglib. Just blame alone. Cause if it is just Blame itself crashing the game without any mods, it's this issue where the java version being used is breaking one mixin. https://github.com/TelepathicGrunt/Blame/issues/4
I'm still trying to think of a workaround for that

**Comment by BugmanBugman** [comment]
Oops, yeah looks like I had a bruh moment. I recently updated blame and added quark into my pack, so I thought the 2 were correlated. It's just the newest Blame. Should I close this?

**Comment by TelepathicGrunt** [comment]
If it is the java thing, yeah I’ll close this now. The workaround is you could try playing with the vanilla launcher, change your third party launcher to use a different java version, or downgrade blame. Sorry about that!
